---
- name: Deinstall Clickhouse & Vector
  hosts: clickhouse
  gather_facts: false

  handlers:
    - name: Systemd Daemon Reload
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

  tasks:
    - block:
        - name: Vector. Stop vector.service daemon
          become: true
          ansible.builtin.service:
            name: vector.service
            state: stopped

        - name: Vector. Deinstall vector binary file
          become: true
          ansible.builtin.file:
            path: "/usr/bin/vector"
            state: absent

        - name: Vector. Remove Vector config
          become: true
          ansible.builtin.file:
            path: "/etc/vector/"
            state: absent

        - name: Vector. Remove vector.service daemon
          become: true
          ansible.builtin.file:
            path: "/lib/systemd/system/vector.service"
            state: absent
          notify: Systemd Daemon Reload

        - name: Vector. Remove Vector data_dir
          become: true
          ansible.builtin.file:
            path: "/var/lib/vector"
            state: absent

        - name: Vector. Remove user vector
          become: true
          ansible.builtin.user:
            name: "{{ vector_os_user }}"
            state: absent
            remove: true
      tags: vector

    - block:
        - name: Clickhouse. Drop database logs
          ansible.builtin.command: "clickhouse-client -q 'drop database logs;'"
          ignore_errors: true
          register: drop_db
          changed_when: drop_db.rc == 0 or drop_db.rc == 81
          failed_when: never

        - name: Clickhouse. Stop clickhouse-server.service daemon
          become: true
          ansible.builtin.service:
            name: clickhouse-server
            state: stopped

        - name: Clickhouse. Deinstall packages
          become: true
          ansible.builtin.apt:
            name:
              - clickhouse-common-static
              - clickhouse-client
              - clickhouse-server
            state: absent
          notify: Systemd Daemon Reload
      tags: clickhouse
